[build]
  image = "louislam/uptime-kuma:1"

[[mounts]]
  source = "kuma_data"
  destination = "/app/data"

[http_service]
  # internal_port = 3001
  # force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
